FROM python:3.11-slim

WORKDIR /app

RUN pip install --upgrade pip -i https://mirrors.aliyun.com/pypi/simple/

COPY requirements.ui.txt .
RUN pip install --no-cache-dir -i https://mirrors.aliyun.com/pypi/simple/ -r requirements.ui.txt

COPY UI/app.py ./app.py

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
